url: https://stephanniec.github.io/stepholio
baseurl: /stepholio/

# Site settings
title: Stephanie L. Chang
email: stephanniechang@gmail.com
description: MSR portfolio.

# Team names, titles and social links
people:
- name: Stephanie L. Chang
  pic: 1
  position: MS in Robotics Student at Northwestern University

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/stephanielchang
  - title: github
    url: https://github.com/stephanniec

# Build settings
markdown: kramdown
permalink: pretty
